pull_request_rules:
  - name: automatic merge on CircleCI success and review
    conditions:
      - base=master
      - status-success=ci/circleci: build
    actions:
      merge:
        method: merge
