pull_request_rules:
  - name: automatic merge on CircleCI success
    conditions:
      - "status-success=ci/circleci: build"
      - base=master
      - files~=^list_url*.json
    actions:
      merge:
        method: merge
        strict: true
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
