pull_request_rules:
  - name: automatic merge on CircleCI success and review
    conditions:
      - "status-success=ci/circleci: build"
    actions:
      merge:
        method: merge
        strict: true